environment_config:
  path: src/app/config/dev_environment_config.dart
  class: DevelopConfig

  fields:
    configName:
      type: String
      default: develop
    baseUrl:
      type: String
      default: https://localhost:8080
    twitchAuthBaseUrl:
      type: String
      default: https://id.twitch.tv/oauth2/
    connectTimeout:
      type: int
      default: 15000
    receiveTimeout:
      type: int
      default: 15000
    defaultLocale:
      type: String
      default: en_US
