environment_config:
  path: src/app/config/prod_environment_config.dart
  class: ProductionConfig

  fields:
    configName:
      type: String
      default: prod
    baseUrl:
      type: String
      default: https://localhost:8080
    twitchAuthBaseUrl:
      type: String
      default: https://id.twitch.tv/oauth2/
    twitchApiBaseUrl:
      type: String
      default: https://api.twitch.tv/
    connectTimeout:
      type: int
      default: 15000
    receiveTimeout:
      type: int
      default: 15000
    defaultLocale:
      type: String
      default: en_US