name: streamer_dashboard
description: "Streamer Dashboard Flutter App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  flutter_gen: ^5.9.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  environment_config: ^3.2.0
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  go_router: ^14.8.0
  yt: ^2.2.5+6
  flutter_inappwebview: ^6.1.5
  system_tray: ^2.0.3
  window_manager: ^0.4.2
  win32: ^5.8.0
  icons_launcher: ^3.0.0
  flutter_acrylic: ^1.1.0
  flutter_keyboard_visibility: ^6.0.0
  url_launcher: ^6.3.1
  external_webview_window:
    git:
      url: https://github.com/PationPrime/external_webview_window.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0

icons_launcher:
  image_path: "assets/app_logo/app_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
      image_path: "assets/app_logo/app_logo.png"
    windows:
      enable: true
      image_path: "assets/app_logo/app_logo.png"

flutter_gen:
  output: lib/src/assets_gen/
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/app_logo/
    - additional_data/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400

  uses-material-design: true
