name: live_stream_widgets
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_gen: ^5.9.0
  go_router: ^14.8.0
  lottie: ^3.3.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4

dependency_overrides:
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0

flutter_gen:
  output: lib/src/assets_gen/
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/images/
    - assets/lottie/

  uses-material-design: true